kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: magento-pv
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-app-content-claim
  namespace: staging
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: magento-pv
  resources:
    requests:
      storage: 5Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: composer
  namespace: staging
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: magento-pv
  resources:
    requests:
      storage: 2Gi